// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { getClientRootComponent } from 'F:/forProjects/nova-design/node_modules/.pnpm/@umijs+renderer-react@4.0.76_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react/dist/server.js';
import { getRoutes } from './core/route';
import { createHistory as createClientHistory } from './core/history';
import { getPlugins as getClientPlugins } from './core/plugin';
import { ServerInsertedHTMLContext } from './core/serverInsertedHTMLContext';
import { PluginManager } from 'F:/forProjects/nova-design/node_modules/.pnpm/umi@4.0.76_@babel+core@7.22.10_@types+node@20.4.7_eslint@8.47.0_postcss@8.4.28_prettier@3.0.2_7vsqt6hn5kkhzf7lhxpip7qaxe/node_modules/umi/client/client/plugin.js';
import createRequestHandler, { createMarkupGenerator } from 'F:/forProjects/nova-design/node_modules/.pnpm/@umijs+server@4.0.76/node_modules/@umijs/server/dist/ssr.js';

let helmetContext;

try {
  helmetContext = require('./core/helmetContext').context;
} catch { /* means `helmet: false`, do noting */ }

const routesWithServerLoader = {
};

export function getPlugins() {
  return getClientPlugins();
}

export function getValidKeys() {
  return ['patchRoutes','patchClientRoutes','modifyContextOpts','modifyClientRenderOpts','rootContainer','innerProvider','i18nProvider','accessProvider','dataflowProvider','outerProvider','render','onRouteChange','modifyCodeSandboxData','modifyStackBlitzData','toSketchJSON',];
}

export function getManifest() {
  return JSON.parse(require('fs').readFileSync('F:/forProjects/nova-design/docs/dist/build-manifest.json', 'utf-8'));
}

export function createHistory(opts) {
  return createClientHistory(opts);
}

// TODO: remove global variable
global.g_getAssets = (fileName) => {
  let m = typeof manifest === 'function' ? manifest() : manifest;
  return m.assets[fileName];
};

const manifest = "production" === 'development' ? getManifest : getManifest();
const createOpts = {
  routesWithServerLoader,
  PluginManager,
  getPlugins,
  getValidKeys,
  getRoutes,
  manifest,
  getClientRootComponent,
  helmetContext,
  createHistory,
  ServerInsertedHTMLContext,
};
const requestHandler = createRequestHandler(createOpts);

export const _markupGenerator = createMarkupGenerator(createOpts);

export default requestHandler;
