// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"blog/components/layout-deivider":{"path":"components/layout-deivider","id":"blog/components/layout-deivider","parentId":"DocLayout"},"blog/components/basic-button":{"path":"components/basic-button","id":"blog/components/basic-button","parentId":"DocLayout"},"blog/guide/index.en-US":{"path":"guide-en","id":"blog/guide/index.en-US","parentId":"DocLayout"},"blog/guide/index.zh-CN":{"path":"guide","id":"blog/guide/index.zh-CN","parentId":"DocLayout"},"blog/index.en-US":{"path":"-en","id":"blog/index.en-US","parentId":"DocLayout"},"blog/index.zh-CN":{"path":"","id":"blog/index.zh-CN","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DemoLayout" */'@/dumi__theme/layouts/DemoLayout')),
'blog/components/layout-deivider': React.lazy(() => import(/* webpackChunkName: "blog__components__layout-deivider.md" */'F:/forProjects/nova-design/docs/blog/components/layout-deivider.md')),
'blog/components/basic-button': React.lazy(() => import(/* webpackChunkName: "blog__components__basic-button.md" */'F:/forProjects/nova-design/docs/blog/components/basic-button.md')),
'blog/guide/index.en-US': React.lazy(() => import(/* webpackChunkName: "blog__guide__index.en-US.md" */'F:/forProjects/nova-design/docs/blog/guide/index.en-US.md')),
'blog/guide/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "blog__guide__index.zh-CN.md" */'F:/forProjects/nova-design/docs/blog/guide/index.zh-CN.md')),
'blog/index.en-US': React.lazy(() => import(/* webpackChunkName: "blog__index.en-US.md" */'F:/forProjects/nova-design/docs/blog/index.en-US.md')),
'blog/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "blog__index.zh-CN.md" */'F:/forProjects/nova-design/docs/blog/index.zh-CN.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
