// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'F:/forProjects/nova-design/docs/node_modules/dumi-theme-antd-style/dist/slots/Footer/index.js';
