// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'F:/forProjects/nova-design/node_modules/.pnpm/dumi@2.2.6_@babel+core@7.22.10_@types+node@20.4.7_eslint@8.47.0_postcss@8.4.28_prettier@3.0.2_ovv5fsrzvzeyksvp3sse4qxiei/node_modules/dumi/theme-default/slots/SocialIcon/index.js';
