name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set node version to 18
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: 'pnpm'

      - run: PUPPETEER_SKIP_DOWNLOAD=1 pnpm install --no-frozen-lockfile
